"""Monitor subset from pyudev 0.24's pyudev/monitor.py and device/_device.py."""

class Context: ...

class Device:
    @property
    def action(self) -> str | None: ...

class Monitor:
    @classmethod
    def from_netlink(cls, context: Context) -> Monitor: ...
    def filter_by(self, subsystem: str) -> None: ...
    def start(self) -> None: ...
    def poll(self, timeout: float | None = None) -> Device | None: ...
